services:
  - type: web
    name: agencia-de-viajes
    env: node
    plan: free
    buildCommand: npm install && npm run build && npm install --prefix server && npm run build --prefix server
    startCommand: NODE_ENV=production node server/dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SERPAPI_KEY
        sync: false
